// Generated by Cypress Author – 2026-04-25
// Tests the StopCard component in isolation, verifying stop name rendering,
// edit/delete controls, and the add-accommodation / add-transport interactions.

import React from "react";
import { StopCard } from "../../app/trip/[tripId]/components/stop/StopCard";
import { TestWrapper, createMockDatabase } from "../support/TestWrapper";
import type {
  AccommodationDocumentType,
  ExpenseDocumentType,
  StopDocumentType,
  TransportDocumentType,
} from "../../lib/rxdb-schema";

// ─── Helpers ────────────────────────────────────────────────────────────────

/** Create a minimal mock RxDB document with the given plain data. */
function mockDoc<T extends object>(data: T) {
  return {
    ...data,
    patch: cy.stub().resolves(),
    remove: cy.stub().resolves(),
  } as unknown as T extends AccommodationDocumentType
    ? AccommodationDocumentType
    : T extends TransportDocumentType
      ? TransportDocumentType
      : T extends ExpenseDocumentType
        ? ExpenseDocumentType
        : StopDocumentType;
}

const mockStop = mockDoc({
  id: "stop-1",
  name: "paris",
  tripId: "trip-1",
  createdAt: 1700000000000,
  updatedAt: 1700000000000,
}) as StopDocumentType;

const defaultProps = {
  index: 1,
  stop: mockStop,
  accommodations: [] as AccommodationDocumentType[],
  transports: [] as TransportDocumentType[],
  expenses: [] as ExpenseDocumentType[],
  defaultCurrency: "USD",
  timezone: "Europe/London",
  addingAccommodation: false,
  addingTransport: false,
  onStartAddAccommodation: cy.stub().as("onStartAddAccommodation"),
  onCancelAddAccommodation: cy.stub().as("onCancelAddAccommodation"),
  onStartAddTransport: cy.stub().as("onStartAddTransport"),
  onCancelAddTransport: cy.stub().as("onCancelAddTransport"),
  onAddAccommodation: cy.stub().as("onAddAccommodation").resolves(),
  onAddTransport: cy.stub().as("onAddTransport").resolves(),
  onEditStopName: cy.stub().as("onEditStopName").resolves(),
  onDeleteStop: cy.stub().as("onDeleteStop").resolves(),
};

// Stub exchange-rate network calls so tests run offline
beforeEach(() => {
  cy.intercept("GET", "https://api.frankfurter.dev/**", {
    body: { rates: { EUR: 0.93, GBP: 0.79 } },
  }).as("exchangeRates");
});

describe("StopCard", () => {
  beforeEach(() => {
    cy.mount(
      <TestWrapper mockDatabase={createMockDatabase()}>
        <StopCard {...defaultProps} />
      </TestWrapper>,
    );
  });

  it("renders stop name → shows capitalised stop name", () => {
    cy.get("[data-cy=stop-card]").should("exist");
    cy.get("[data-cy=stop-name]").should("contain.text", "Paris");
  });

  it("shows index number → displays 1 in the badge", () => {
    cy.get("[data-cy=stop-card]").contains("1");
  });

  it("shows edit and delete buttons → both controls are visible", () => {
    cy.get("[data-cy=edit-stop-button]").should("exist");
    cy.get("[data-cy=delete-stop-button]").should("exist");
  });

  it("clicking edit → shows name input with current value", () => {
    cy.get("[data-cy=edit-stop-button]").click();
    cy.get("[data-cy=stop-name-input]")
      .should("be.visible")
      .and("have.value", "paris");
  });

  it("submits edited name → calls onEditStopName with new value", () => {
    cy.get("[data-cy=edit-stop-button]").click();
    cy.get("[data-cy=stop-name-input]").clear().type("Lyon");
    cy.get("[data-cy=stop-name-save]").click();
    cy.get("@onEditStopName").should("have.been.calledOnceWith", "Lyon");
  });

  it("cancels edit → hides input without calling onEditStopName", () => {
    cy.get("[data-cy=edit-stop-button]").click();
    cy.get("[data-cy=stop-name-cancel]").click();
    cy.get("[data-cy=stop-name]").should("exist");
    cy.get("@onEditStopName").should("not.have.been.called");
  });

  it("clicking add-accommodation → calls onStartAddAccommodation", () => {
    cy.get("[data-cy=add-accommodation-button]").click();
    cy.get("@onStartAddAccommodation").should("have.been.calledOnce");
  });

  it("clicking add-transport → calls onStartAddTransport", () => {
    cy.get("[data-cy=add-transport-button]").click();
    cy.get("@onStartAddTransport").should("have.been.calledOnce");
  });

  it("shows empty stays message when no accommodations", () => {
    cy.contains("No stays for this stop.").should("exist");
  });

  it("shows empty journeys message when no transports", () => {
    cy.contains("No journeys for this stop.").should("exist");
  });
});
