// Generated by Cypress Author – 2026-04-25
// Tests the TripNameEditor component in isolation, verifying display,
// edit mode, save, and cancel behaviours.

import React from "react";
import { TripNameEditor } from "../../app/trip/[tripId]/components/trip-header/TripNameEditor";
import { TestWrapper } from "../support/TestWrapper";

describe("TripNameEditor", () => {
  const defaultProps = {
    tripName: "Paris Adventure",
    onSave: cy.stub().as("onSave").resolves(),
    onExport: cy.stub().as("onExport").resolves(),
  };

  beforeEach(() => {
    cy.mount(
      <TestWrapper>
        <TripNameEditor {...defaultProps} />
      </TestWrapper>,
    );
  });

  it("displays the trip name → renders name in heading", () => {
    cy.get("[data-cy=trip-name-display]").should("contain.text", "Paris Adventure");
  });

  it("shows edit and export buttons → both controls are visible", () => {
    cy.get("[data-cy=trip-name-edit]").should("exist");
    cy.get("[data-cy=trip-export]").should("exist");
  });

  it("clicks edit → switches to input mode with current name pre-filled", () => {
    cy.get("[data-cy=trip-name-edit]").click();
    cy.get("[data-cy=trip-name-input]")
      .should("be.visible")
      .and("have.value", "Paris Adventure");
  });

  it("edits and saves → calls onSave with the new name", () => {
    cy.get("[data-cy=trip-name-edit]").click();
    cy.get("[data-cy=trip-name-input]").clear().type("Rome Escape");
    cy.get("[data-cy=trip-name-save]").click();
    cy.get("@onSave").should("have.been.calledOnceWith", "Rome Escape");
  });

  it("cancels edit → reverts to display mode without calling onSave", () => {
    cy.get("[data-cy=trip-name-edit]").click();
    cy.get("[data-cy=trip-name-input]").clear().type("Discard Me");
    cy.get("[data-cy=trip-name-cancel]").click();
    cy.get("[data-cy=trip-name-display]").should("contain.text", "Paris Adventure");
    cy.get("@onSave").should("not.have.been.called");
  });

  it("save button is disabled when input is empty → prevents saving blank name", () => {
    cy.get("[data-cy=trip-name-edit]").click();
    cy.get("[data-cy=trip-name-input]").clear();
    cy.get("[data-cy=trip-name-save]").should("be.disabled");
  });

  it("clicks export → calls onExport", () => {
    cy.get("[data-cy=trip-export]").click();
    cy.get("@onExport").should("have.been.calledOnce");
  });
});
