/**
 * Cypress custom commands shared across E2E and component tests.
 *
 * Generated by Cypress Author – 2026-04-25
 */

// Make this file a module so global augmentations are valid
export {};

// ─── Type augmentation ───────────────────────────────────────────────────────

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Cypress {
    interface Chainable {
      /**
       * Loads the predefined JSON test fixture data from the Cypress task.
       */
      getTestData(): Chainable;

      /**
       * Clears all IndexedDB databases in the browser so E2E tests start
       * with a clean application state.
       */
      clearAppStorage(): Chainable;
    }
  }
}

// ─── Commands ────────────────────────────────────────────────────────────────

Cypress.Commands.add("getTestData", () => {
  return cy.task("getTestData");
});

Cypress.Commands.add("clearAppStorage", () => {
  return cy.window().then((win) => {
    // Clear IndexedDB (used by RxDB/Dexie)
    return new Promise<void>((resolve) => {
      const req = win.indexedDB.deleteDatabase("fzt-db");
      req.onsuccess = () => resolve();
      req.onerror = () => resolve(); // resolve even on error so tests continue
      req.onblocked = () => resolve();
    });
  });
});
