/**
 * Cypress custom commands shared across E2E and component tests.
 *
 * Generated by Cypress Author – 2026-04-25
 */

// Make this file a module so global augmentations are valid
export {};

// ─── Type augmentation ───────────────────────────────────────────────────────

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Cypress {
    interface Chainable {
      /**
       * Loads the predefined JSON test fixture data from the Cypress task.
       */
      getTestData(): Chainable;

      /**
       * Clears all IndexedDB databases in the browser so E2E tests start
       * with a clean application state.
       */
      clearAppStorage(): Chainable;
    }
  }
}

// ─── Commands ────────────────────────────────────────────────────────────────

Cypress.Commands.add("getTestData", () => {
  return cy.task("getTestData");
});

Cypress.Commands.add("clearAppStorage", () => {
  return cy.window().then((win) => {
    const deleteDb = (name: string) =>
      new Promise<void>((resolve) => {
        const req = win.indexedDB.deleteDatabase(name);
        req.onsuccess = () => resolve();
        req.onerror = () => resolve();
        req.onblocked = () => resolve();
      });

    const databasesPromise = win.indexedDB.databases
      ? win.indexedDB.databases()
      : Promise.resolve([]);

    return databasesPromise.then((dbs) => {
      const names = new Set<string>(["fzt-db"]);
      dbs.forEach((db) => {
        if (
          typeof db.name === "string" &&
          db.name.startsWith("rxdb-dexie-fzt-db--")
        ) {
          names.add(db.name);
        }
      });
      return Promise.all([...names].map((name) => deleteDb(name))).then(
        () => undefined,
      );
    });
  });
});
