/**
 * Cypress component test support file.
 * Runs before each component spec.
 *
 * Generated by Cypress Author – 2026-04-25
 */
import { mount } from "cypress/react";
import "./commands";

// Make this file a module so global augmentations are valid
export {};

// Augment the Cypress namespace for cy.mount()
declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Cypress {
    interface Chainable {
      mount: typeof mount;
    }
  }
}

Cypress.Commands.add("mount", mount);
