/**
 * Cypress E2E test support file.
 * Runs before each E2E spec.
 *
 * Generated by Cypress Author – 2026-04-25
 */
import "./commands";

// Suppress Next.js hydration mismatch errors that occur in dev mode.
// These are non-fatal rendering differences (e.g. Google Fonts link) and
// should not cause E2E tests to fail.
Cypress.on("uncaught:exception", (err) => {
  if (
    err.message.includes("Hydration failed") ||
    err.message.includes("hydration") ||
    err.message.includes("did not match")
  ) {
    return false;
  }
  return true;
});
