/**
 * Test database utilities for Cypress tests.
 * Provides predefined seed data and CRUD helpers for use in both
 * component and E2E tests.
 *
 * Generated by Cypress Author – 2026-04-25
 */
import type { RxDatabase } from "rxdb";
import type { DatabaseCollections } from "../../lib/rxdb-database";
import type {
  TripDocument,
  StopDocument,
  AccommodationDocument,
  TransportDocument,
  ExpenseDocument,
  UserSettingsDocument,
} from "../../lib/rxdb-schema";
import { USER_SETTINGS_ID } from "../../lib/rxdb-schema";

// ─── Predefined seed data ────────────────────────────────────────────────────

export const TEST_TRIP_ID = "test-trip-001";
export const TEST_TRIP_ID_2 = "test-trip-002";
export const TEST_STOP_ID = "test-stop-001";
export const TEST_STOP_ID_2 = "test-stop-002";
export const TEST_ACCOMMODATION_ID = "test-accommodation-001";
export const TEST_TRANSPORT_ID = "test-transport-001";
export const TEST_EXPENSE_ID = "test-expense-001";

const NOW = 1700000000000;

export const TEST_TRIPS: TripDocument[] = [
  {
    id: TEST_TRIP_ID,
    name: "Paris Adventure",
    startDate: "2025-06-01",
    startLocation: "London",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: TEST_TRIP_ID_2,
    name: "Tokyo Trip",
    startDate: "2025-09-15",
    createdAt: NOW + 1000,
    updatedAt: NOW + 1000,
  },
];

export const TEST_STOPS: StopDocument[] = [
  {
    id: TEST_STOP_ID,
    name: "Paris",
    tripId: TEST_TRIP_ID,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: TEST_STOP_ID_2,
    name: "Lyon",
    tripId: TEST_TRIP_ID,
    createdAt: NOW + 500,
    updatedAt: NOW + 500,
  },
];

export const TEST_ACCOMMODATIONS: AccommodationDocument[] = [
  {
    id: TEST_ACCOMMODATION_ID,
    name: "Hotel du Louvre",
    price: 150,
    currency: "EUR",
    checkIn: "2025-06-01T14:00",
    checkOut: "2025-06-05T11:00",
    stopId: TEST_STOP_ID,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const TEST_TRANSPORTS: TransportDocument[] = [
  {
    id: TEST_TRANSPORT_ID,
    name: "Eurostar to Paris",
    type: "train",
    price: 80,
    currency: "GBP",
    departureDateTime: "2025-06-01T09:00",
    arrivalDateTime: "2025-06-01T12:15",
    stopId: TEST_STOP_ID,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const TEST_EXPENSES: ExpenseDocument[] = [
  {
    id: TEST_EXPENSE_ID,
    tripId: TEST_TRIP_ID,
    stopId: TEST_STOP_ID,
    name: "Dinner at Le Jules Verne",
    category: "food",
    price: 120,
    currency: "EUR",
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const TEST_SETTINGS: UserSettingsDocument = {
  id: USER_SETTINGS_ID,
  defaultCurrency: "USD",
  language: "en",
  timezone: "Europe/London",
  dateFormat: "dd/MM/yyyy",
};

// ─── Seed function ───────────────────────────────────────────────────────────

export type SeedResult = {
  trips: TripDocument[];
  stops: StopDocument[];
  accommodations: AccommodationDocument[];
  transports: TransportDocument[];
  expenses: ExpenseDocument[];
  settings: UserSettingsDocument;
};

/**
 * Inserts all predefined test data into the provided RxDB database.
 * Upserts are used so the function is safe to call multiple times.
 */
export async function seedData(
  db: RxDatabase<DatabaseCollections>,
): Promise<SeedResult> {
  await Promise.all([
    ...TEST_TRIPS.map((t) => db.trips.upsert(t)),
    ...TEST_STOPS.map((s) => db.stops.upsert(s)),
    ...TEST_ACCOMMODATIONS.map((a) => db.accommodations.upsert(a)),
    ...TEST_TRANSPORTS.map((t) => db.transports.upsert(t)),
    ...TEST_EXPENSES.map((e) => db.expenses.upsert(e)),
    db.settings.upsert(TEST_SETTINGS),
  ]);

  return {
    trips: TEST_TRIPS,
    stops: TEST_STOPS,
    accommodations: TEST_ACCOMMODATIONS,
    transports: TEST_TRANSPORTS,
    expenses: TEST_EXPENSES,
    settings: TEST_SETTINGS,
  };
}

// ─── CRUD helpers ────────────────────────────────────────────────────────────

/**
 * Insert a single trip into the database and return the inserted document.
 */
export async function insertTrip(
  db: RxDatabase<DatabaseCollections>,
  trip: TripDocument,
) {
  return db.trips.insert(trip);
}

/**
 * Insert a single stop into the database.
 */
export async function insertStop(
  db: RxDatabase<DatabaseCollections>,
  stop: StopDocument,
) {
  return db.stops.insert(stop);
}

/**
 * Remove all trips, stops, accommodations, transports and expenses.
 */
export async function clearAllData(db: RxDatabase<DatabaseCollections>) {
  const [trips, stops, accommodations, transports, expenses] =
    await Promise.all([
      db.trips.find().exec(),
      db.stops.find().exec(),
      db.accommodations.find().exec(),
      db.transports.find().exec(),
      db.expenses.find().exec(),
    ]);

  await Promise.all([
    ...trips.map((d) => d.remove()),
    ...stops.map((d) => d.remove()),
    ...accommodations.map((d) => d.remove()),
    ...transports.map((d) => d.remove()),
    ...expenses.map((d) => d.remove()),
  ]);
}
