/**
 * Mock provider wrappers for Cypress component tests.
 * These allow mounting components that depend on SettingsProvider and
 * NextIntlClientProvider without requiring a live database.
 *
 * Generated by Cypress Author – 2026-04-25
 */
import React from "react";
import { NextIntlClientProvider } from "next-intl";
import { SettingsContext } from "../../lib/SettingsProvider";
import { DatabaseContext } from "../../lib/DatabaseProvider";
import enMessages from "../../messages/en.json";
import type { DateFormat } from "../../lib/rxdb-schema";
import type { MyDatabase } from "../../lib/rxdb-database";

// Default mock settings matching the test database seed
export const DEFAULT_MOCK_SETTINGS = {
  defaultCurrency: "USD",
  language: "en",
  timezone: "Europe/London",
  dateFormat: "dd/MM/yyyy" as DateFormat,
  analyticsConsent: false,
  cookiesConsent: false,
  setDefaultCurrency: () => {},
  setLanguage: () => {},
  setTimezone: () => {},
  setDateFormat: () => {},
  setAnalyticsConsent: () => {},
  setCookiesConsent: () => {},
};

/**
 * Minimal mock database for use in component tests.
 * Stubs the collection methods that components call at render time.
 */
export function createMockDatabase(): MyDatabase {
  const makeCollection = () => ({
    insert: () => Promise.resolve({}),
    upsert: () => Promise.resolve({}),
    find: () => ({
      exec: () => Promise.resolve([]),
      $: { subscribe: () => ({ unsubscribe: () => {} }) },
      sort: () => ({ exec: () => Promise.resolve([]) }),
    }),
    findOne: () => ({
      exec: () => Promise.resolve(null),
      $: { subscribe: () => ({ unsubscribe: () => {} }) },
    }),
  });

  return {
    trips: makeCollection(),
    stops: makeCollection(),
    accommodations: makeCollection(),
    transports: makeCollection(),
    expenses: makeCollection(),
    settings: makeCollection(),
  } as unknown as MyDatabase;
}

type MockSettingsOverrides = Partial<typeof DEFAULT_MOCK_SETTINGS>;

type TestWrapperProps = {
  children: React.ReactNode;
  settingsOverrides?: MockSettingsOverrides;
  mockDatabase?: MyDatabase;
};

/**
 * Wraps a component under test with:
 * - NextIntlClientProvider (English messages)
 * - A mock SettingsContext (avoids need for a real database)
 * - An optional mock DatabaseContext (pass in custom stubs as needed)
 */
export function TestWrapper({
  children,
  settingsOverrides = {},
  mockDatabase,
}: TestWrapperProps) {
  const settingsValue = { ...DEFAULT_MOCK_SETTINGS, ...settingsOverrides };
  const db = mockDatabase ?? createMockDatabase();

  return (
    <NextIntlClientProvider locale="en" messages={enMessages}>
      <DatabaseContext.Provider value={db}>
        <SettingsContext.Provider value={settingsValue}>
          {children}
        </SettingsContext.Provider>
      </DatabaseContext.Provider>
    </NextIntlClientProvider>
  );
}
