// Generated by Cypress Author – 2026-04-25
// E2E tests for the home page: trip list, search, filters, and the
// create-trip dialog flow.

describe("Home page", () => {
  beforeEach(() => {
    // Reset IndexedDB so each test starts with a clean state
    cy.clearAppStorage();

    // Stub exchange-rate API to avoid network dependency
    cy.intercept("GET", "https://api.frankfurter.dev/**", {
      body: { rates: { EUR: 0.93, GBP: 0.79, USD: 1 } },
    }).as("exchangeRates");

    // Visit with localStorage set to prevent tutorial dialog from showing
    cy.visit("/", {
      onBeforeLoad(win) {
        win.localStorage.setItem("fzt-tutorial-seen", "true");
      },
    });
  });

  // ─── Hero section ───────────────────────────────────────────────────────

  it("displays the page hero → hero title is visible", () => {
    cy.contains("Trips").should("be.visible");
  });

  it("shows the plan-trip button → button is visible", () => {
    cy.get("[data-cy=plan-trip-button]").should("be.visible");
  });

  // ─── Create trip dialog ─────────────────────────────────────────────────

  it("opens create-trip dialog → dialog is shown", () => {
    cy.get("[data-cy=plan-trip-button]").click();
    cy.get("[data-cy=create-trip-dialog]").should("be.visible");
    cy.contains("Create a new trip").should("be.visible");
  });

  it("creates a trip with a name → navigates to the new trip page", () => {
    cy.get("[data-cy=plan-trip-button]").click();
    cy.get("[data-cy=trip-name-input]").type("My Test Trip");
    cy.get("[data-cy=create-trip-submit]").click();
    // Should navigate away from home to the trip page
    cy.url().should("include", "/trip/");
  });

  it("creates a trip with name and first stop → navigates to trip page", () => {
    cy.get("[data-cy=plan-trip-button]").click();
    cy.get("[data-cy=trip-name-input]").type("Road Trip 66");
    cy.get("[data-cy=first-stop-input]").type("Chicago");
    cy.get("[data-cy=create-trip-submit]").click();
    cy.url().should("include", "/trip/");
  });

  // ─── Search & filters ───────────────────────────────────────────────────

  it("search input is visible → can type in it", () => {
    cy.get("[data-cy=search-input]").should("be.visible").type("Paris");
    cy.get("[data-cy=search-input]").should("have.value", "Paris");
  });

  it("filter tabs are visible → all four tab options rendered", () => {
    cy.get("[data-cy=filter-tabs]").within(() => {
      cy.contains("All").should("exist");
      cy.contains("Upcoming").should("exist");
      cy.contains("Ongoing").should("exist");
      cy.contains("Past").should("exist");
    });
  });

  // ─── Empty state ─────────────────────────────────────────────────────────

  it("shows empty state when no trips exist → empty state message visible", () => {
    // The app uses IndexedDB which starts empty in a fresh test environment.
    // If there are existing trips, the empty state won't show, but we
    // still verify the search input filters correctly.
    cy.get("body").then(($body) => {
      if ($body.find("[data-cy=empty-state]").length) {
        cy.get("[data-cy=empty-state]").should("be.visible");
        cy.contains("No trips yet.").should("be.visible");
      } else {
        // At least one trip card is rendered
        cy.get("[data-cy=trip-card]").should("have.length.at.least", 1);
      }
    });
  });

  // ─── Trip cards ──────────────────────────────────────────────────────────

  it("trip cards have stable data attributes → data-trip-id present", () => {
    cy.get("body").then(($body) => {
      if ($body.find("[data-cy=trip-card]").length) {
        cy.get("[data-cy=trip-card]")
          .first()
          .should("have.attr", "data-trip-id");
      }
    });
  });

  it("clicking a trip card → navigates to the trip detail page", () => {
    cy.get("body").then(($body) => {
      if ($body.find("[data-cy=trip-card]").length) {
        cy.get("[data-cy=trip-card]").first().click();
        cy.url().should("include", "/trip/");
      }
    });
  });
});
