// Generated by Cypress Author – 2026-04-25
// E2E tests for trip details page behavior: creating stops and stop items.

describe("Trip details page", () => {
  const resetDbAndVisitHome = () => {
    cy.clearAppStorage();

    cy.intercept("GET", "https://api.frankfurter.dev/**", {
      body: { rates: { EUR: 0.93, GBP: 0.79, USD: 1 } },
    }).as("exchangeRates");

    cy.visit("/", {
      onBeforeLoad(win) {
        win.localStorage.setItem("fzt-tutorial-seen", "true");
      },
    });
  };

  const createTripAndOpenDetails = (tripName: string, firstStop: string) => {
    cy.get("[data-cy=plan-trip-button]").click();
    cy.get("[data-cy=trip-name-input]").clear().type(tripName);
    cy.get("[data-cy=first-stop-input]").clear().type(firstStop);
    cy.get("[data-cy=create-trip-submit]").click();

    cy.url().should("include", "/trip/");
    cy.contains(tripName).should("be.visible");
    cy.get("[data-cy=stop-name]").should("contain.text", firstStop);
  };

  describe("stops", () => {
    beforeEach(() => {
      resetDbAndVisitHome();
      createTripAndOpenDetails("Trip Details - Stops", "Paris");
    });

    it("creates an additional stop → new stop card is rendered", () => {
      cy.get("input[placeholder='Add another stop...']").type("Rome");
      cy.contains("button", "Add stop").click();

      cy.get("[data-cy=stop-name]").should("contain.text", "Rome");
      cy.get("[data-cy=stop-card]").should("have.length", 2);
    });
  });

  describe("stop items", () => {
    beforeEach(() => {
      resetDbAndVisitHome();
      createTripAndOpenDetails("Trip Details - Items", "Berlin");
    });

    it("creates accommodation → accommodation item appears in stop", () => {
      cy.get("[data-cy=stop-card]").first().within(() => {
        cy.get("[data-cy=add-accommodation-button]").click();
      });

      cy.get("input#accommodation-name").type("Hotel Aurora");

      cy.contains("label", "Check-out")
        .parent()
        .find("button")
        .first()
        .click();
      cy.contains("button", "Tomorrow").click();

      cy.contains("button", "Add stay").click();

      cy.get("[data-cy=stop-card]").first().contains("Hotel Aurora").should("be.visible");
    });

    it("creates transport → transport item appears in stop", () => {
      cy.get("[data-cy=stop-card]").first().within(() => {
        cy.get("[data-cy=add-transport-button]").click();
      });

      cy.get("input#transport-name").type("Flight LH123");
      cy.contains("button", "Add journey").click();

      cy.get("[data-cy=stop-card]").first().contains("Flight LH123").should("be.visible");
    });

    it("creates expense → expense item appears in stop", () => {
      cy.get("[data-cy=stop-card]").first().within(() => {
        cy.contains("button", "Add expense").click();
      });

      cy.get("input[placeholder='Expense name']").type("Dinner");
      cy.contains("button", "Save").click();

      cy.get("[data-cy=stop-card]").first().contains("Dinner").should("be.visible");
    });
  });
});
